### ISSUE TITLE
Add spellcheck

### ISSUE THREAD

**Issue by JafarAbdi** [JafarAbdi/projects_generator#13]
```yaml
- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
    - id: codespell
      args: ['--write-changes']
      exclude: \.(svg|pyc)$
```
