### ISSUE TITLE
Use YAML file to specify the templates

### ISSUE THREAD

**Issue by JafarAbdi** [JafarAbdi/projects_generator#20]
```YAML
templates:
  - name: TEMPLATE_NAME
    path: PATH # w.r.t. templates_path
    data: # variables ? should specify default value .?
      - DATA_1
      - DATA_2
      .
      .
      .
    files:
      - name:
        output_filename: # could use inja syntax
      .
      .
      .
  - .
  - .
  - .  
```
